# Generated by Django 3.0.3 on 2020-07-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200703_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='signup',
        ),
    ]
